SELECT STUDENTS.STUDENT_ID, STUDENTS.NAME,
COUNT(ENROLLMENTS.COURSE_ID) AS TOTAL_COURSES,
SUM(NVL(ENROLLMENTS.COURSE_ID,0)) AS SUM_OF_COURSE_IDS,
AVG(STUDENTS.AGE) AS AVERAGE_AGE,
MIN(STUDENTS.AGE) AS MINIMUM_AGE,
MAX(STUDENTS.AGE) AS MAXIMUM_AGE 
FROM STUDENTS
LEFT JOIN ENROLLMENTS
ON STUDENTS.STUDENT_ID=ENROLLMENTS.STUDENT_ID
GROUP BY STUDENTS.STUDENT_ID, STUDENTS.NAME;
