SELECT STUDENT_ID, NAME,AGE, ROW_NUMBER() OVER (ORDER BY AGE DESC) AS ROW_NUM,
RANK() OVER (ORDER BY AGE DESC) AS RANK_NUM,
DENSE_RANK() OVER (ORDER BY AGE DESC) AS DENSE_RANK_NUM,
PERCENT_RANK() OVER (ORDER BY AGE DESC) AS PERCENT_RANK
 FROM STUDENTS;
